const data={
  brand:'Birendra Sah',
  role:'Secure Future Advisor',
  headline:'Your trust today,\n your security for tomorrow.',
  intro:'Helping families and businesses plan with confidence through thoughtful insurance guidance.',
  personalIntro:'Hello, I am Birendra Sah (NATIONAL LIFE INSURANCE AGENT). I am your trusted SecureFuture Advisor. I help individuals, families, and businesses make confident decisions for a more secure future.',
  photo:'assets/profile.jpg',
  credential:{title:'Insurance officer/advisor credential',description:'Professional identification and proof of insurance expertise.',photo:'assets/credential.jpg'},
  experience:'12+',policies:'450+',branch:'Inaruwa',
  currentCompanies:[{company:'NATIONAL LIFE INSURANCE',role:'Insurance agent/advisor',branch:'Inaruwa Branch',dates:'Present',logo:'assets/current-company-logo.png'}],
  pastCompanies:[{company:'Sanima Reliance life inc.',role:'Insurance agent/advisor',branch:'Inaruwa Branch',dates:'2077-2079',logo:'assets/previous-company-1.png'},{company:'Surya Jyoti life inc.',role:'Insurance agent/advisor',branch:'Inaruwa Branch ',dates:'2073-2076',logo:'assets/previous-company-2.png'}],
  aboutTitle:'Guidance built on trust.',
  aboutText:'I help clients understand their options, protect their loved ones, and prepare for the future with clear, responsible advice.',
  certificates:[{title:'Top of the month(2082)',photo:'assets/certificate-1.jpg'},{title:'Ceo club member(2080/81)',photo:'assets/certificate-2.jpg'}],
  award:{title:'Collective award(2080/81/82)',photo:'assets/award.jpg'},
  achievements:[{title:'450+ Families Protected',description:'A milestone built through long-term relationships and trusted guidance.',year:'2073-till now',photo:'assets/500-families-protected.jpg'},{title:'Life Insurance Specialist',description:'Certified expertise in family protection and financial planning.',year:'2073-till now',photo:'assets/life-insurance-specialist.jpg'}],
  email:'birenshah367@gmail.com',whatsapp:'+9779807709307',phone:'9818880370',facebook:'https://www.facebook.com/birendra.sah.250634'
};
const $=id=>document.getElementById(id);
const moneyFlow=document.querySelector('.money-flow');
['$','EUR','BTC','$','GBP','BTC','JPY','$'].forEach((symbol,index)=>{const coin=document.createElement('span');coin.textContent=symbol;coin.style.left=(index*13-3)+'%';coin.style.animationDuration=(9+index%5)+'s';coin.style.animationDelay=(-index*1.7)+'s';moneyFlow.appendChild(coin);});
function number(value){return String(value||'').replace(/\D/g,'');}
function safeUrl(value){try{const url=new URL(value);return ['http:','https:'].includes(url.protocol)?url.href:'#';}catch{return '#';}}
function renderCompanies(id,companies){const container=$(id);container.replaceChildren();companies.forEach(item=>{const card=document.createElement('div');card.className=id==='currentCompanies'?'company-item current-company-card':'company-item';if(item.logo){const logo=document.createElement('img');logo.className='company-logo';logo.src=item.logo;logo.alt=(item.company||'Company')+' logo';card.appendChild(logo);}const name=document.createElement('strong');name.textContent=item.company||'Company';const details=document.createElement('span');details.textContent=[item.role,item.branch,item.dates].filter(Boolean).join(' · ');card.append(name,details);container.appendChild(card);});}
function renderCards(id,items,maxItems){const container=$(id);const visibleItems=items.slice(0,maxItems).filter(item=>item&&((item.title&&item.title.trim())||(item.description&&item.description.trim())||(item.photo&&item.photo.trim())));container.innerHTML=visibleItems.map((item,index)=>`<article class="card" data-reveal>${item.photo?`<img class="project-img project-photo" src="${item.photo}" alt="${item.title||'Certificate or award'}">`:''}${item.year?`<span class="tags">${item.year}</span>`:''}${item.title?`<h3>${item.title}</h3>`:''}${item.description?`<p class="muted">${item.description}</p>`:''}</article>`).join('');container.querySelectorAll('img').forEach(image=>image.addEventListener('error',()=>image.closest('.card').remove()));}
function setupImageViewer(){const viewer=$('imageViewer');const image=$('viewerImage');document.addEventListener('click',event=>{const source=event.target.closest('.project-photo');if(!source)return;image.src=source.src;image.alt=source.alt;viewer.showModal();});$('viewerClose').addEventListener('click',()=>viewer.close());viewer.addEventListener('click',event=>{if(event.target===viewer)viewer.close();});}
function render(){
  $('brand').textContent=data.brand;const dot=document.createElement('span');dot.textContent='.';$('brand').appendChild(dot);$('footerName').textContent=data.brand;$('role').textContent=data.role;$('headline').textContent=data.headline;$('intro').textContent=data.intro;$('personalIntro').textContent=data.personalIntro;
  $('profilePhoto').src=data.photo;$('credentialPhoto').src=data.credential.photo;$('credentialPhoto').alt=data.credential.title;$('credentialTitle').textContent=data.credential.title;$('credentialDescription').textContent=data.credential.description;
  $('experience').textContent=data.experience;$('policies').textContent=data.policies;$('branch').textContent=data.branch;$('aboutTitle').textContent=data.aboutTitle;$('aboutText').textContent=data.aboutText;renderCompanies('currentCompanies',data.currentCompanies);renderCompanies('pastCompanies',data.pastCompanies.slice(0,2));
  $('whatsappLink').href=data.whatsapp?'https://wa.me/'+number(data.whatsapp):'#';$('whatsappNumber').textContent=data.whatsapp?' · '+number(data.whatsapp):'';$('phoneLink').href=data.phone?'tel:'+number(data.phone):'#';$('phoneNumber').textContent=data.phone?number(data.phone):'';$('emailLink').href='mailto:'+data.email;$('emailLink').textContent='✉️ '+data.email;$('facebookLink').href=safeUrl(data.facebook);
  renderCards('certificates',[...data.certificates,data.award],3);$('projects').innerHTML=data.achievements.map((item,index)=>`<article class="card" data-reveal>${item.photo?`<img class="project-img project-photo" src="${item.photo}" alt="${item.title}">`:`<div class="project-img" style="filter:hue-rotate(${index*75}deg)"></div>`}<span class="tags">${item.year}</span><h3>${item.title}</h3><p class="muted">${item.description}</p></article>`).join('');
  enableCardMotion();}
function enableCardMotion(){if(matchMedia('(prefers-reduced-motion: reduce)').matches||!matchMedia('(pointer: fine)').matches)return;document.querySelectorAll('.card,.profile-frame,.credential-card,.quick-contact-card,.company-item').forEach(card=>{if(card.dataset.motionReady)return;card.dataset.motionReady='true';card.onpointermove=event=>{const rect=card.getBoundingClientRect(),x=event.clientX-rect.left,y=event.clientY-rect.top;card.style.setProperty('--mx',x+'px');card.style.setProperty('--my',y+'px');card.style.transform=`perspective(700px) translateY(-8px) rotateX(${((y/rect.height)-.5)*-8}deg) rotateY(${((x/rect.width)-.5)*8}deg)`;};card.onpointerleave=()=>card.style.transform='';});}
render();setupImageViewer();$('year').textContent=new Date().getFullYear();const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('show');observer.unobserve(entry.target);}}));document.querySelectorAll('[data-reveal]').forEach(element=>observer.observe(element));